version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./frontend/build/ s3:b1-frontend

artifacts:
  files:
    - "frontend/build/*"
  discard-paths: no