version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run build && aws s3 sync build/ s3://b1-front-end

  artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: build