version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
      - aws lambda update-function-code \--function-name  Dummy \--s3-bucket backendartifacts --s3-key Build.zip

artifacts:
  files:
    - "**/*"
  discard-paths: no