AWSTemplateFormatVersion: '2010-09-09'
Description: SmartPhotoAlbum

Resources:
    FrontEnd:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bucket1-front-end
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    PhotoStore:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bucket2-photo-store
        AccessControl: PublicRead

    LambdaOne:
      Type: AWS::Lambda::Function
      Properties:
        Runtime: python3.9
        Code:
          S3Bucket: lf1-code
          S3Key: build.zip
        Role: arn:aws:iam::<Role-ID>:role/service-role/LF1-index-photos-role-i1ch33u5
        Handler: LF1-index-photos/lambda_function.lambda_handler
        Layers:
          - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-requests:2

    LambdaTwo:
      Type: AWS::Lambda::Function
      Properties:
        Runtime: python3.9
        Code:
          S3Bucket: lf2-code
          S3Key: build.zip
        Role: arn:aws:iam::<Role-ID>:role/service-role/LF2-search-photos-role-c8oyawwj
        Handler: LF2-search-photos/lambda_function.lambda_handler
        Layers:
          - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-requests:2

    PhotoIndexer:
      Type: AWS::OpenSearchService::Domain
      Properties:
        DomainName: photos-idx
        ClusterConfig:
          InstanceType: t3.small.search
          InstanceCount: 1
        EBSOptions:
          EBSEnabled: true
          VolumeSize: 10
          VolumeType: gp2

    SearchBot:
      Type: AWS::Lex::Bot
      Properties:
        IdleSessionTTLInSeconds: 300
        Name: LexSearchBot
        RoleArn: AWSServiceRoleForLexV2Bots_H90CVEW230C
        DataPrivacy:
          ChildDirected: false
        RoleArn: <Role-ARN>

    LabelRecognition:
      Type: AWS::Rekognition::Project
      Properties:
        ProjectName: photo-labeler
